CREATE TABLE IF NOT EXISTS tb_config(
  ID_CONFIG INTEGER,
  EQUIPAMENTO_SEL TEXT,
);


CREATE TABLE IF NOT EXISTS tb_equipamento(
  CHAVE_EQUIPAMENTO TEXT,
  TIPO_EQUIPAMENTO TEXT,
  CAPACIDADE_MAXIMA REAL,
  DESCRICAO_EQUIPAMENTO TEXT,
  CHAVE_ERP TEXT,
  ESTADO_EQUIPAMENTO BOOLEAN
);


CREATE TABLE IF NOT EXISTS tb_local(
  CHAVE_LOCAL TEXT,
  DESCRICAO_LOCAL TEXT,
  CHAVE_ERP TEXT,
  TIPO_LOCAL TEXT,
  ESTADO_LOCAL BOOLEAN
);

CREATE TABLE IF NOT EXISTS tb_material(
  CHAVE_MATERIAL TEXT,
  DESCRICAO_MATERIAL TEXT,
  CHAVE_ERP TEXT,
  DENSIDADE_ESPECIFICA REAL,
  FORNECEDOR_MATERIAL TEXT,
  ESTADO_MATERIAL BOOLEAN,
  UNIDADE_MATERIAL TEXT
);

CREATE TABLE IF NOT EXISTS auth_user(
  USER_ID INTEGER,
  GROUP_ID INTEGER,
  EMAIL TEXT,
  PASSWORD TEXT
);

--DROP TABLE tb_equipamento;

INSERT INTO tb_equipamento(CHAVE_EQUIPAMENTO, TIPO_EQUIPAMENTO, CAPACIDADE_MAXIMA, DESCRICAO_EQUIPAMENTO, CHAVE_ERP, ESTADO_EQUIPAMENTO)
VALUES ('VE0070','VEÍCULO', 16, 'MERCEDES AXOR - CAÇAMBA 16M3', 'VE0070',1);

INSERT INTO tb_equipamento(CHAVE_EQUIPAMENTO, TIPO_EQUIPAMENTO, CAPACIDADE_MAXIMA, DESCRICAO_EQUIPAMENTO, CHAVE_ERP, ESTADO_EQUIPAMENTO)
VALUES ('VE0029','VEÍCULO', 12, 'FORD CARGO - CAÇAMBA 12M3', 'VE0029',1);

INSERT INTO tb_equipamento(CHAVE_EQUIPAMENTO, TIPO_EQUIPAMENTO, CAPACIDADE_MAXIMA, DESCRICAO_EQUIPAMENTO, CHAVE_ERP, ESTADO_EQUIPAMENTO)
VALUES ('VE0046','VEÍCULO', 12, 'MERCEDES AXOR 3131 - CAÇAMBA 16M3 88888', 'VE0046',1);

INSERT INTO tb_local(CHAVE_LOCAL, DESCRICAO_LOCAL, CHAVE_ERP, TIPO_LOCAL, ESTADO_LOCAL)
VALUES ('077','PEDREIRA - FALCHETTI', '077', 'FORNECEDOR', 1);

INSERT INTO tb_local(CHAVE_LOCAL, DESCRICAO_LOCAL, CHAVE_ERP, TIPO_LOCAL, ESTADO_LOCAL)
VALUES ('207','OLAVO - SANTA ROSA', '207', 'TRECHO', 0);

INSERT INTO tb_material(CHAVE_MATERIAL, DESCRICAO_MATERIAL, CHAVE_ERP, DENSIDADE_ESPECIFICA,FORNECEDOR_MATERIAL,ESTADO_MATERIAL,UNIDADE_MATERIAL)
VALUES ('111213','MACADAME', '111213', 1300.00, '23', 1, 'M3.');

INSERT INTO tb_material(CHAVE_MATERIAL, DESCRICAO_MATERIAL, CHAVE_ERP, DENSIDADE_ESPECIFICA,FORNECEDOR_MATERIAL,ESTADO_MATERIAL,UNIDADE_MATERIAL)
VALUES ('111215','BASE', '111214', 1500.00, '23', 1, 'M3.');

INSERT INTO tb_material(CHAVE_MATERIAL, DESCRICAO_MATERIAL, CHAVE_ERP, DENSIDADE_ESPECIFICA,FORNECEDOR_MATERIAL,ESTADO_MATERIAL,UNIDADE_MATERIAL)
VALUES ('111214','MACADAME', '111214', 1200.00, '23', 0, 'T.');

INSERT INTO tb_config(ID_CONFIG, EQUIPAMENTO_SEL)
VALUES (1,'Nenhum');

INSERT INTO auth_user(USER_ID, GROUP_ID, EMAIL, PASSWORD)
VALUES (1,1,'gustavo.ronconi@bclempreendimentos.com.br', '12218083');

INSERT INTO auth_user(USER_ID, GROUP_ID, EMAIL, PASSWORD)
VALUES (2,2,'douglas.castanhel@bclempreendimentos.com.br', '12218083');

--DELETE FROM auth_user WHERE USER_ID = 2;

--SELECT * FROM tb_material;

--SELECT * FROM tb_equipamento;

--SELECT * FROM tb_config;

--SELECT * FROM auth_user;