#:import C kivy.utils.get_color_from_hex

<ButtonTechRoad@Button>:
    orientation: "horizontal"
    background_color: C("#1874CD")
    background_normal: ""

<InputTechRoad@TextInput>:
    orientation: "horizontal"
    background_color: C("#E0FFFF")
    background_normal: ""
    foreground_color: C("#1874CD")
    font_name: "consola"
    font_size: 60
    cursor_color: C("#1874CD")
<TextTechRoad@Label>:
    orientation: "horizontal"
    font_name: "consola"